"""empty message

Revision ID: 1e97e4a7a700
Revises: 316c91593660
Create Date: 2024-06-21 23:04:28.830002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e97e4a7a700'
down_revision = '316c91593660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_united', sa.Column('status', sa.String(), nullable=True))
    op.drop_index('ix_card_united_patient_id', table_name='card_united')
    op.drop_column('card_united', 'patient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_united', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_card_united_patient_id', 'card_united', ['patient_id'], unique=False)
    op.drop_column('card_united', 'status')
    # ### end Alembic commands ###
