"""empty message

Revision ID: 316c91593660
Revises: 797bfa1b5f13
Create Date: 2024-06-21 23:04:13.618533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316c91593660'
down_revision = '797bfa1b5f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
