"""add cause card

Revision ID: 797bfa1b5f13
Revises: c5ae72b22938
Create Date: 2024-06-01 01:05:22.874324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797bfa1b5f13'
down_revision = 'c5ae72b22938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
