"""add mkb

Revision ID: ab94b349f80c
Revises: 
Create Date: 2023-12-06 17:06:30.633777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab94b349f80c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_united', sa.Column('mkb', sa.String(), nullable=True))
    op.drop_index('ix_Doctors_username', table_name='doctors')
    op.create_unique_constraint(None, 'doctors', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='unique')
    op.create_index('ix_Doctors_username', 'doctors', ['username'], unique=False)
    op.drop_column('card_united', 'mkb')
    # ### end Alembic commands ###
