"""empty message

Revision ID: c5ae72b22938
Revises: 6908358bb771
Create Date: 2024-06-01 01:04:05.085211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ae72b22938'
down_revision = '6908358bb771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_united', sa.Column('cause', sa.String(), nullable=True))
    op.drop_column('patient', 'cause')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('cause', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('card_united', 'cause')
    # ### end Alembic commands ###
