"""add model in card

Revision ID: cb763177bd17
Revises: 1e97e4a7a700
Create Date: 2024-06-22 11:47:59.983043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb763177bd17'
down_revision = '1e97e4a7a700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_united', sa.Column('crew', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_united', 'crew')
    # ### end Alembic commands ###
